plugins {
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'java'
}

group 'com.tea-mc'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url = 'https://mvnrepository.com/artifact/net.md-5/bungeecord-api' }
    maven { url = 'https://jitpack.io' }
}

dependencies {
    implementation 'org.javacord:javacord:3.4.0'
    compileOnly 'net.md-5:bungeecord-api:1.16-R0.3'
}

test {
    useJUnitPlatform()
}