
Auto-Helper:
  Questions:
    '1':
      Messages:
        - "ip"
        - "ip?"
        - "what is ip"
        - "what is ip?"
        - "what is server ip"
        - "what is server ip?"
        - "what is the server ip"
        - "what is the server ip?"
        - "how do i join tea-mc"
        - "how do i join tea-mc?"
        - "how do i join server"
        - "how do i join server?"
        - "how do i join the server"
        - "how do i join the server?"
        - "how connect"
        - "how connect?"
        - "how to connect"
        - "how to connect?"
        - "how join"
        - "how join?"
        - "how to join"
        - "how to join?"
      Answer: "You can join the server using **play.tea-mc.com**!"
    '2':
      Messages:
        - "version"
        - "version?"
        - "what server version"
        - "what server version?"
        - "what is server version"
        - "what is server version?"
        - "what is the server version"
        - "what is the server version?"
        - "what version to use"
        - "what version to use?"
        - "what version should I use"
        - "what version should I use?"
      Answer: "You can join the server using **ANY** version! However, it is recommended that you use: **1.16.5 for Skyblock** and **1.8.9 for OP-Factions & KitPvP**."


Auto-Mod:
  MassMention:
    Max-Mentions: 10 # If user exceeds this amount of mentions in 1 message then they'll get banned from the server.
  Whitelisted:
    Domains:
      - "youtube.com"
      - "youtu.be"
      - "tea-mc.com"
      - "discord.com"
      - "discordapp.com"
      - "twitch.tv"
      - "imgur.com"
      - "gyazo.com"
      - "tenor.com"
      - "giphy.com"
      - "medal.tv"
      - "wikipedia.org"
      - "twitter.com"
      - "instagram.com"
      - "reddit.com"
  Blacklisted:
    Pages:
      - "discord.com/invite"
    Words:
      - "nigger"
      - "nigga"
      - "fucking"
      - "fuck"
      - "coon"
      - "faggot"
      - "fgt"
      - "kys"


Tickets:
  Types:
    Support:
      Category: 882644591088635924
      Support-Roles:
        - 696078834860032060
      Button: "Create Ticket"
      Panel-Embed:
        Title: "Support Tickets  :tickets:"
        Description:
          - "Need assistance? Create a support ticket and one of our staff members will help you as soon as possible!"
          - ""
          - "**Valid reasons to open a support ticket:**"
          - ":question: Questions/Support."
          - ":gift: Claiming Payouts/Giveaways."
          - ":exclamation: Player Reports."
          - ":bug: Bug Reports."
          - "<:logo:711350804472266833> Anything related to Tea-MC."
          - ""
          - "**Notes:**"
          - ":stopwatch: Staff try to respond to tickets as soon as possible so please refrain from tagging staff members unless its urgent."
          - ":information_source: You should try to provide as much information as possible so our staff team can give you an instant response, You can send screenshots, videos, gifs, logs, etc."
      Ticket-Embed:
        Title: "Hello %name%!  <:TeaMC:673883531541348352>"
        Description:
          - "Please describe the reason for your ticket"
          - "and our staff team will get back to you as soon as possible."
          - ""
          - "You can close the ticket by clicking the 'Close Ticket' button below."
    Applications:
      Category: 882644621795155980
      Support-Roles:
        - 696078834860032060
      Button: "Create Application"
      Panel-Embed:
        Title: "Staff & Builder Applications  :hammer:"
        Description:
          - "Tea-MC is always in constant development and we're always looking to expand our team!"
          - ""
          - "**Applications Template & Requirements:**"
          - ":hammer: Staff/Builder Applications: https://tea-mc.com/threads/staff-application-template-open.8/."
          - ""
          - "**Please ensure you meet the requirements before creating a ticket - It is also recommended to prepare your application before creating the ticket to reduce wait times. Once ready click the 'Create Application' button below.**"
          - "**Goodluck with your application!**"
      Options:
        Text: "What position are you applying for?"
        List:
          Staff:
            Support-Roles: []
            Name: "Staff App"
            Description: "For staff applications."
            Emoji: "🔨"
            Variable:
              - "**Applications Template & Requirements:**"
              - ":hammer: Staff Application: https://tea-mc.com/threads/staff-application-template-open.8/."
          Builder:
            Support-Roles:
              - 656473633161609216
            Name: "Builder App"
            Description: "For builder applications."
            Emoji: "👷🏻"
            Variable:
              - "**Applications Template & Requirements:**"
              - ":construction_worker::skin-tone-1: Builder Application: https://tea-mc.com/threads/staff-application-template-open.8/."
      Ticket-Embed:
        Title: "Hello %name%!  <:TeaMC:673883531541348352>"
        Description:
          - "Thank you for your interest in Tea-MC %option% Team."
          - ""
          - "%variable%"
          - ""
          - "Please post your application here."
          - ""
          - "Keep in mind discord has a 2k character limit so you may need to split it (Unless you have nitro then it is 4k)."
    Appeals:
      Category: 882644525552640041
      Support-Roles:
        - 696078834860032060
        - 883683061311610880
      Button: "Create Appeal"
      Panel-Embed:
        Title: "Punishments Appeals  :hammer:"
        Description:
          - "if you have recently been punished (Last 3 months) you may appeal it."
          - ""
          - "**Appeal Template:**"
          - "Username: (Your in-game name)."
          - "Ban/Mute Reason: (The reason you were banned/muted)."
          - "Guilty: (Yes/No)."
          - "Personal Statement: (Use this to express your opinion on why the punishment is incorrect or to admit your wrong doings)."
          - "Proof: (Only if Not Guilty - Image/Video proof disputing your ban reason)."
          - ""
          - "**Please prepare your appeal before opening a ticket to help decrease wait times, once ready click the 'Create Appeal' button below.**"
          - ""
          - "**Notes:**"
          - ":receipt: If you are providing proof, please make sure that it is verifiable by our staff team."
          - ":negative_squared_cross_mark: You may not appeal the same punishment twice. The staff team decision is final."
          - ":x: Just because your punishment reason is not specifically included in the rules that doesn't mean its invalid."
          - ":hammer: Lying in an appeal will cause your appeal to be instantly denied, and if staff time is wasted due to it, your punishment could be further extended upon."
          - ":red_circle: You should use your personal statement to express your opinion on why your punishment is incorrect or to admit to your wrong doings and explain why we should allow you back onto the network."
          - ""
          - "**Goodluck with your appeal! We hope to see you on the network again soon!**"
      Ticket-Embed:
        Title: "Hello %name%!  <:TeaMC:673883531541348352>"
        Description:
          - "Please ensure that you have used the Punishment Appeal template and that you are honest. If we find you to be dishonest, your appeal will be instantly denied and we might even extend your punishment."
          - ""
          - "**Appeal Template:**"
          - "Username: (Your in-game name)."
          - "Ban/Mute Reason: (The reason you were banned/muted)."
          - "Guilty: (Yes/No)."
          - "Personal Statement: (Use this to express your opinion on why the punishment is incorrect or to admit your wrong doings)."
          - "Proof: (Only if Not Guilty - Image/Video proof disputing your ban reason)."
